language: node_js
sudo: required
node_js:
  - "8.11.3"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential

before_install:
  - npm install -g npm@latest
  - npm install -g truffle@beta

install:
  - npm install

script:
  - truffle test
